name: Integration Tests

on:
  push:
    branches: [ main ]

jobs:
  docker:
    strategy:
      fail-fast: false
      matrix:
        docker_version:
          - "20.10"
          - "19.03"
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Setup Docker
        uses: docker-practice/actions-setup-docker@master

      - name: Prune Docker System
        run: docker system prune -a -f

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run Tests
        run: ./gradlew allTests